// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5nEaIDQ9M0Ese_dw4DjDkmfCDCLT78E',
    appId: '1:328364827739:web:8f08ca9d37957d506b0b7e',
    messagingSenderId: '328364827739',
    projectId: 'sofe4640u-finalproject',
    authDomain: 'sofe4640u-finalproject.firebaseapp.com',
    databaseURL: 'https://sofe4640u-finalproject-default-rtdb.firebaseio.com',
    storageBucket: 'sofe4640u-finalproject.appspot.com',
    measurementId: 'G-48DE99MXQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_gd-zhO-OcswIIcUhHb2uW0AvrOzD4NI',
    appId: '1:328364827739:android:04897cb1ef2b281c6b0b7e',
    messagingSenderId: '328364827739',
    projectId: 'sofe4640u-finalproject',
    databaseURL: 'https://sofe4640u-finalproject-default-rtdb.firebaseio.com',
    storageBucket: 'sofe4640u-finalproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnjpqOBHu_AJXKWB-LRROjzTvd9RWPTtU',
    appId: '1:328364827739:ios:9cead9903b297b0f6b0b7e',
    messagingSenderId: '328364827739',
    projectId: 'sofe4640u-finalproject',
    databaseURL: 'https://sofe4640u-finalproject-default-rtdb.firebaseio.com',
    storageBucket: 'sofe4640u-finalproject.appspot.com',
    iosClientId: '328364827739-rh3e1h2hduvetvga78rmcldogn2clbbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sofe4640Finalproject',
  );
}
